### ISSUE TITLE
GUI not starting up

### ISSUE THREAD

**Issue by kelassal** [Jessewb786/Silaty#12]
I have installed the latest version on ubuntu 20.04 using the Debian package but every time I try starting the application i am getting the spinning wheel for a while and but the application GUI never shows up. I know the application is running and I get notification of the prayer times but I cannot see the GUI thus I cannot edit any of the settings to fit my location\timezone.

I have tried installing it through snap but I get the exact same behavior.

**Comment by AXeL-dev** [comment]
Hey,

This is a normal behavior since the app starts minimized to the tray icon panel by default, so if you cannot access the app from the tray icon you can disable the minimized startup behavior by editing `.silaty` file in your root directory & set the `minimized` value to `0`. To do that in one line command, 1st open a terminal then past:
```
sed -i 's/minimized = 1/minimized = 0/g' .silaty
```

**Edit**: you have to relaunch the app after that (you can kill its process using your system monitor then open it again, or using `silaty-indicator` command).

**Comment by kelassal** [comment]
The un-minimizing command worked perfectly. Thank you very much. I am xrdp'ing into the system so I couldn't see it in the tray.

I have noticed another issue (maybe I should create a separate log for it). The Fajar and Shuruk time are set in PM time.

![Silaty](https://user-images.githubusercontent.com/43716155/99930099-19773680-2d0d-11eb-8b74-b750d3045838.PNG)

**Comment by AXeL-dev** [comment]
okay, which location are you using? also which version have you tried on? the snap or the debian package (because the deb package is outdated).

**Comment by kelassal** [comment]
Location is "Edmonton Namao". I have used the debian package.

**Comment by AXeL-dev** [comment]
Okay so here is what i get when i try on the latest version:

![image](https://user-images.githubusercontent.com/30635693/100020576-53fdd380-2de0-11eb-9d82-4c19b77016e7.png)

This is somehow expected since i've faced that bug by past & fixed it on the following commit https://github.com/LinuxForGeeks/Silaty/commit/e60e354e7469b4284868b409f53ad69a6d3692f6 but i didn't update the debian package, so until i do you have two options:
- use the snap package
- or update your debian installed version manually (based on changes in the [commit]( https://github.com/LinuxForGeeks/Silaty/commit/e60e354e7469b4284868b409f53ad69a6d3692f6)). You can find the files on `/usr/share/silaty/` folder.

**Comment by kelassal** [comment]
I have installed it from snap and it is working fine right now. Thank You!

**Comment by AXeL-dev** [comment]
You're welcome :wink:
